version: 2.0.{build}
configuration: Release
skip_branch_with_pr: true
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  Version: $(APPVEYOR_BUILD_VERSION)
  GithubRepo: $(APPVEYOR_REPO_NAME)
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1 -Configuration Release -ScriptArgs '--packageversion="%APPVEYOR_BUILD_VERSION%"'
test:
  assemblies:
    - '**\Carnac.Tests.dll'
artifacts:
- path: deploy\Chocolatey\*.nupkg
  name: ChocoPackage
- path: deploy\GitHub\*.zip
  name: ZipPackage
- path: deploy\Squirrel\Releases\*
  name: SquirrelPackage
deploy:
- provider: GitHub
  auth_token:
    secure: tvr7i0kJpT3SAdYG037M6zU1g6FYXHAUUaseqBTUzasqsUo6mumdcW+huf5/351p
  artifact: ZipPackage
  draft: false
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: tvr7i0kJpT3SAdYG037M6zU1g6FYXHAUUaseqBTUzasqsUo6mumdcW+huf5/351p
  artifact: SquirrelPackage
  draft: false
  on:
    branch: master
- provider: NuGet
  server: https://chocolatey.org/
  api_key:
    secure: sMCceYyOHQxaJMpcWBGmbGkbB6aYToUWm3rqfLv1ZZaeToqM2PAz1or18hnJbon0
  skip_symbols: true
  artifact: ChocoPackage
  on:
    branch: master
